services:
  goker-ledger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goker-ledger
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - RUST_LOG=info
    env_file:
      - .env
    networks:
      - goker-network

networks:
  goker-network:
    external: true
